# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(default='', primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=100)),
                ('first_name', models.CharField(default='first name', max_length=100)),
                ('last_name', models.CharField(default='last name', max_length=100)),
                ('gender', models.IntegerField(default=0)),
                ('dob', models.DateField(default='yyyy-MM-dd', max_length=50)),
                ('phone_no', models.CharField(default='0000000000', max_length=10)),
                ('country_code', models.CharField(default='91', max_length=5)),
                ('email', models.CharField(default='enter email', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('bio', models.CharField(default='add your bio', max_length=100)),
                ('join_date', models.DateField(default='yyyy-MM-dd', max_length=50)),
                ('total_views', models.IntegerField(default=0)),
                ('profile_pic', models.CharField(default='', max_length=1000)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
