# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20170505_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updatation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='posts/%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('interest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mobile.InterestsContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.users')),
            ],
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest_content',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Post'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.users'),
        ),
    ]
